/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface JhnWebslides {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (enter: boolean, reveal: boolean) => Promise<boolean>;
        "hideContent": () => Promise<void>;
        "lazyLoadContent": () => Promise<void>;
        "revealContent": () => Promise<void>;
        /**
          * An example of a custom property
         */
        "value": string;
    }
}
declare global {
    interface HTMLJhnWebslidesElement extends Components.JhnWebslides, HTMLStencilElement {
    }
    var HTMLJhnWebslidesElement: {
        prototype: HTMLJhnWebslidesElement;
        new (): HTMLJhnWebslidesElement;
    };
    interface HTMLElementTagNameMap {
        "jhn-webslides": HTMLJhnWebslidesElement;
    }
}
declare namespace LocalJSX {
    interface JhnWebslides {
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
        /**
          * An example of a custom property
         */
        "value"?: string;
    }
    interface IntrinsicElements {
        "jhn-webslides": JhnWebslides;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "jhn-webslides": LocalJSX.JhnWebslides & JSXBase.HTMLAttributes<HTMLJhnWebslidesElement>;
        }
    }
}
